### ISSUE TITLE
MimeType rule fails with large uploads

### ISSUE THREAD

**Issue by juniwalk** [nepada/file-upload-control#143]
Hi,
I implemented your component in my app and I am having issue which I don't know how to solve.

When I set a rule to limit allowed mimetypes and I try to upload larger file, it fails on first chunk because FileUpload does not have mimetype available. I don't know if I should report this in nette/forms or here. If it is fixed in nette/forms and the rule fails, the upload fails.

```php
$form->addFileUpload('upload')
	->addRule($form::MimeType, 'web.message.file-unknown-mimetype', $this::AllowedMimeTypes)
	->addRule($this->checkFreeSpace(...), 'web.message.file-size-limit-reached')
	->addRule($form::MaxFileSize, 'web.message.file-maximum-size', 5e7)	// 50 MB
	->addRule($form::MaxLength, 'web.message.file-maximum-number', 6);
```

The fail occurs in [Validator.php](https://github.com/nette/forms/blob/master/src/Forms/Validator.php) in nette/forms because strtolower does not expect null.
```php
public static function validateMimeType(Controls\UploadControl $control, $mimeType): bool
{
	$mimeTypes = is_array($mimeType) ? $mimeType : explode(',', $mimeType);
	foreach (static::toArray($control->getValue()) as $file) {
		$type = strtolower($file->getContentType());
		if (!in_array($type, $mimeTypes, true) && !in_array(preg_replace('#/.*#', '/*', $type), $mimeTypes, true)) {
			return false;
		}
	}

	return true;
}
```

**Comment by xificurk** [comment]
Hi, thanks for the report. This is definitely a bug of this package.

**Comment by juniwalk** [comment]
@xificurk Good to know I did not misreport this. Is there anything I can do to help?

**Comment by xificurk** [comment]
I think, I've identified the problem, but still need to double check it and add tests. I'll have the fix out within a couple of days.

**Comment by xificurk** [comment]
@juniwalk Can you please test current master to verify it fixes the problem in your setup?

**Comment by juniwalk** [comment]
@xificurk Works great, thank you!
