### ISSUE TITLE
Disable submit while upload in progress

### ISSUE THREAD

**Issue by juniwalk** [nepada/file-upload-control#144]
Is there a way to disable submit button until all uploads are finished or canceled?

If I submit form when the upload is still in progress it adds already uploaded files however large file that was still in progress of uploading finishes upload (based on Tracy AJAX requests) but then is lost.

**Comment by xificurk** [comment]
Right now, the only way would be to hook directly into the events produced by underlying blueimp-file-upload like it is done for refreshing UI state, see https://github.com/nepada/file-upload-control/blob/master/src/assets/js/index.js#L36

I've got a couple of ideas how to make this a bit more safe. One of them is adding check into nette forms client side validation to prevent submission when there are uploads still in progress (that should cover also other cases then clicking the submit button).

**Comment by xificurk** [comment]
I believe most of the issues should be addressed by https://github.com/nepada/file-upload-control/releases/tag/v1.8.0

**Comment by juniwalk** [comment]
Looks great, I will check it out tomorrow. Thanks!

**Comment by juniwalk** [comment]
Works great, however setting translated message is kinda hard.

I tried this:
```php
$form->addFileUpload('upload')
	->addRule(ClientSide::NO_UPLOAD_IN_PROGRESS, 'web.message.file-upload-active')
```

However that does not seem to work, I had to do this:
```php
$fileUpload = $form->addFileUpload('upload');

foreach ($fileUpload->getRules() as $rule) {
	if ($rule->validator <> ClientSide::class.'::noUploadInProgress') {
		continue;
	}

	$rule->message = 'web.message.file-upload-active';
}
```

Is there a way to make this easier? Shall I create another issue?

**Comment by xificurk** [comment]
All error messages should be automatically translated by Translator (if set to form). It should be possible to directly translate it.

**Comment by juniwalk** [comment]
Alright, thanks.
