### ISSUE TITLE
MimeType validation error

### ISSUE THREAD

**Issue by juniwalk** [nepada/file-upload-control#148]
Hi, me again with validation issues. :)

I had edge case where MimeType returned was `null` and Validator has failed because of `strtolower` call.

There should probably be `return $mimeType ?? '';` so it is always string.

![image](https://github.com/nepada/file-upload-control/assets/451918/ca89e4f9-abb6-430a-8d45-3ac3511de77b)

**Comment by xificurk** [comment]
That's a bug in validator from `nette/forms` (see your stack trace). This would fail even with normal FileUploadControl. This needs to be addressed in Nette itself.

**Comment by juniwalk** [comment]
@xificurk Oh I just thought that it was issue inside FileUploadControl. Alright thanks.
